apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xhjl6t706-python 
  janus-idp.io/tekton: xhjl6t706-python
  backstage.io/kubernetes-id: xhjl6t706-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xhjl6t706-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml