apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xhjl6t706-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xhjl6t706-python 
  name: xhjl6t706-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xhjl6t706-python 
